version: 0.2

phases:
  install:
    commands:
      - echo Install
  pre_build:
    commands:
      - echo Install depend
  build:
    commands:
      - echo Buid

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: taiga